[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --include=dev",
    "cd server && npm ci --include=dev"
]

[phases.build]
cmds = [
    "cd server && npm run build"
]

[start]
cmd = "cd server && npm start" 